# Generated by Django 4.2.7 on 2023-12-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surmname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('postal_address', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
